name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build_deps:
    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO: Linking is not working on linux.
#          - os: ubuntu-latest
#            task: linkReleaseExecutableLinuxX64
          - os: macOS-13
            task: linkReleaseExecutableMacosX64
            target: 'macosX64'
          - os: macOS-14
            task: linkReleaseExecutableMacosArm64
            target: 'macosArm64'
          # TODO: build on 'windows-latest'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - uses: gradle/actions/setup-gradle@v3
        continue-on-error: true

      - name: Uninstall Homebrew curl
        if: matrix.os == 'macOS-13' || matrix.os == 'macOS-14'
        # Forces libcurl to be statically linked by uninstalling the dynamic libs
        run: brew uninstall --ignore-dependencies curl

      - run: ./gradlew ${{ matrix.task }}

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: stacker-${{ matrix.target }}
          path: build/bin/${{ matrix.target }}/releaseExecutable/stacker.kexe
          if-no-files-found: error
